Prettify a bit

diff --git a/bin/clean-backups b/bin/clean-backups
--- a/bin/clean-backups
+++ b/bin/clean-backups
@@ -3,10 +3,11 @@
 
 p="${DON_PATH:-$HOME/.config/etcdon}"
 
-echo "Removing all but the ten most recent postgres backups..."
+echo -n "Removing all but the ten most recent postgres backups..."
+
 cd "$p"/local/postgres || { echo "FAIL: cannot access directory"; exit 1; }
 if ls -tp | grep -v '/$' |tail -n +11 | xargs -I {} rm -v -- {}; then
-    echo "OK"; exit 0
+    echo "[OK]"; exit 0
 else
-    echo "FAIL"; exit 1
+    echo "[FAIL]"; exit 1
 fi
diff --git a/bin/gather-secrets b/bin/gather-secrets
--- a/bin/gather-secrets
+++ b/bin/gather-secrets
@@ -4,11 +4,10 @@
 mpath=/home/mastodon/live
 p="${DON_PATH:-$HOME/.config/etcdon}"
 
-echo "WARNING: This file is sensitive--don't check it into a public git repo!"
-echo "Gathering secrets file..."
+echo -n "Gathering secrets file, don't check it into a public git repo..."
 
 if  rsync -ac root@"$DON_HOST":"$mpath"/.env.production "$p"/local/; then
-    echo "OK"; exit 0
+    echo "[OK]"; exit 0
 else
-    echo "FAIL"; exit 1
+    echo "[FAIL]"; exit 1
 fi
diff --git a/bin/gather-uploads b/bin/gather-uploads
--- a/bin/gather-uploads
+++ b/bin/gather-uploads
@@ -2,10 +2,9 @@
 #
 
 p="${DON_PATH:-$HOME/.config/etcdon}"
-upath=/home/mastodon/live/public/system
+uploads_path=/home/mastodon/live/public/system
 
-echo "WARNING: Mastodon may have many gigs of user files--proceed with caution!"
-echo "Gathering user files, this may take a while..."
+echo -n "Gathering user uploads, this may take a while..."
 
 # rsync(1)'s -c checksums the destination file against the error file to ensure
 # error-free delivery. This is best for data integrity, but it does slow down
@@ -32,10 +31,10 @@ echo "Gathering user files, this may take a while..."
 # app instability if restored to the server. For now I am only going to run
 # --delete-after manually and not provide a script to guard against footguns.
 #
-r="rsync -ac"
+r="rsync -ac --exclude=cache/ root@$DON_HOST"
 
-if $r --exclude=cache/ root@"$DON_HOST":"$upath"/ "$p"/local/user/; then
-    echo "OK"; exit 0
+if $r:"$uploads_path"/ "$p"/local/uploads/; then
+    echo "[OK]"; exit 0
 else
-    echo "FAIL"; exit 1
+    echo "[FAIL]"; exit 1
 fi
diff --git a/bin/install-crontab-postgres b/bin/install-crontab-postgres
--- a/bin/install-crontab-postgres
+++ b/bin/install-crontab-postgres
@@ -4,14 +4,14 @@
 p="${DON_PATH:-$HOME/.config/etcdon}"
 s="ssh root@$DON_HOST"
 
-echo "Installing crontab for postgres user..."
+echo -n "Installing crontab for postgres user..."
 scp -q "$p"/etc/crontab-postgres root@"$DON_HOST":~/crontab-postgres
 
 $s /bin/sh<<EOF
 mkdir -p backups && crontab -u postgres crontab-postgres
 if crontab -u postgres -l | diff pgc - ; then
-    echo 'OK'; rm crontab-postgres; exit 0
+    echo '[OK]'; rm crontab-postgres; exit 0
 else
-    echo 'FAIL'; exit 1
+    echo '[FAIL]'; exit 1
 fi
 EOF
